<?php

class Kalinich_Surprise_Model_Surprise extends Mage_Core_Model_Abstract {

    public function _construct()
    {
        parent::_construct(); // TODO: Change the autogenerated stub
        $this->_init('kalinich_surprise/surprise');
    }

    public function getProductColletion($productId) {

        $collection = Mage::getModel('kalinich_surprise/surprise')->getCollection()
            ->addFieldToSelect('product_id')
            ->addFieldToFilter('surprise_id', $productId);
        foreach ($collection as $value) {
            $product[] = $value->getProductId();
        }

        return $product;
    }
}